### ISSUE TITLE
Error 500 when calling Rest API

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#105]
**Describe the bug**
Since the latest update, I am getting an error with some calls to the REST API.

> 
> My site is hosted on siteground and the Siteground optimizer plugin encounters erros when trying to connect to the Rest API.
> 
> This shows on my error_log after a failed call to domain.com/wp-json/siteground-optimizer/v1/fetch-options
> 
> [20-May-2021 19:56:54 UTC] PHP Fatal error: Uncaught Error: Call to a member function needs_shipping() on null in /home/customer/www/domain.com/public_html/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-gateway-amazon-payments-advanced.php:1572
> 
> Is there a solution other than editing the plugin code to check if WC()->cart exists on this line?
> 
> $needs_shipping = WC()->cart->needs_shipping();
> 
> thanks in advance.
> 
> 
> 
> Follow up, I added the conditional and get a new error on line 661 where another call to WC() is made.
> So I added…..
> 
> public function get_checkout_session_id() {
>         $session_key = $this->get_checkout_session_key();
>         // add this escape
>         if ( is_null( WC()->session ) ) {
>             return false;
>         }
>         return WC()->session->get( $session_key, false );
>     }
> but this doesn’t look a good solution.

**Sometimes WC() elements won't be initialized (eg: WC()->cart , or WC()->checkout ). Add checks for this.**

Ticket: https://wordpress.org/support/topic/error-500-when-calling-rest-api/

**Comment by ChristianAF** [comment]
```
[24-May-2021 05:22:40 UTC] PHP Fatal error:  Uncaught Exception: Unable to send request, underlying exception of getaddrinfo() thread failed to start
 in /home/customer/www/domain.com/public_html/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/vendor/amzn/amazon-pay-api-sdk-php/Amazon/Pay/API/HttpCurl.php:73
Stack trace:
#0 /home/customer/www/domain.com/public_html/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/vendor/amzn/amazon-pay-api-sdk-php/Amazon/Pay/API/HttpCurl.php(60): Amazon\Pay\API\HttpCurl->execute(Resource id #1403)
#1 /home/customer/www/domain.com/public_html/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/vendor/amzn/amazon-pay-api-sdk-php/Amazon/Pay/API/HttpCurl.php(97): Amazon\Pay\API\HttpCurl->httpSend('GET', 'https://pay-api...', NULL, Array)
#2 /home/customer/www/domain.com/public_html/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/vendor/amzn/amazon-pay-api-sdk-php/Amazon/Pay/API/Client.php(473): Amazon\Pay\API\HttpCurl->invokeCurl( in /home/customer/www/domain.com/public_html/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/vendor/amzn/amazon-pay-api-sdk-php/Amazon/Pay/API/HttpCurl.php on line 73
```

**Comment by ChristianAF** [comment]
Customer of the ticket https://wordpress.org/support/topic/error-500-when-calling-rest-api/ . Told us that is working fine since 2.0.3v
